// Re-export all shared types from @cold-blood-cast/shared
// This file serves as a barrel export for the frontend.
export type {
    ApiSuccessResponse,
    ApiErrorDetail,
    ApiErrorResponse,
    ApiResponse,
    PaginationMeta,
    PaginatedResponse,
    SystemRoleName,
    SuggestionStatus,
    AnnouncementType,
    RegistrationMode,
    AuthUser,
    AuthTokens,
    LoginPayload,
    RegisterPayload,
    AuthMeResponse,
    FeatureTierInfo,
    Role,
    RoleDetail,
    FeatureFlag,
    Tag,
    Announcement,
    ApiKey,
    ApiKeyWithSecret,
    CreateApiKeyPayload,
    AdminUser,
    AdminUserDetail,
    PlatformStats,
    UserGrowthPoint,
    AuditLogEntry,
    SystemSettingEntry,
    InviteCode,
    InviteCodeUse,
    CreateInviteCodePayload,
    AccessRequest,
    LegalDocumentKey,
    ImpressumMetadata,
    LegalDocument,
    AdminLegalDocument,
    UpdateLegalDocumentPayload,
    PublicLegalDocument,
    LegalDocumentLink,
    DataExportStatus,
    DataExportInfo,
} from "@cold-blood-cast/shared";
