name: Tests

on:
    workflow_call:

jobs:
    backend:
        name: Backend Tests
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - name: Generate Prisma client
              run: pnpm --filter @cold-blood-cast/backend db:generate

            - name: Run backend tests
              run: pnpm --filter @cold-blood-cast/backend test

    frontend:
        name: Frontend Tests
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - name: Prepare Nuxt
              run: pnpm --filter @cold-blood-cast/frontend postinstall

            - name: Run frontend tests
              run: pnpm --filter @cold-blood-cast/frontend test:run
